configMapGenerator:
- files:
  - application.yml
  name: 82267289-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: ceappacr.azurecr.io/82267289
  newTag: "202411270536"
- name: cepgstapacr.azurecr.io/82267289
  newTag: "202408120727"
