apiVersion : apps/v1
kind: Deployment
metadata:
  name: 82267289
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 82267289
  template:
    metadata:
      labels:
        app: 82267289
    spec:
      containers:
        - name: 82267289
          image: cepgstapacr.azurecr.io/82267289
          ports:
          - containerPort: 8080
